### ISSUE TITLE
Investigate Haveno's compliance status

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#11]
Haveno will not have custody of people's funds, so we should be fairly safe from regulations from that point of view, but regulations in crypto are continuously changing and we need to make sure Haveno's structure won't create legal problems to its users and maintainers.

It's important to make sure that Haveno stays compliant. We already had some (encouraging) first opinions, but we should have more talks with compliance expert and make them analyse Haveno and its structure, so that we can make changes and improvements if/where necessary.

Possible next steps:

- Talk with people in `#monero-policy`, asking for pointers and suggestions.
- Contact compliance experts and analyse Haveno and the best ways to make sure it's compliant now and (as much as possible) in the future. Would be probably a good idea to hire somebody for the job. In that case we need a cost estimate.
- Follow regional-specific regulations, which could get harsher in the US, but not in other countries and adapt accordingly.

Ideas and opinions, especially from people interested in compliance, are welcome.

**Comment by erciccione** [comment]
The new proposed rules for europe (to be confirmed by the European parlament): https://www.consilium.europa.eu/media/53105/st14067-en21.pdf. The summary on reddit: https://old.reddit.com/r/CryptoCurrency/comments/r218s7/the_most_important_piece_of_regulation_on/

**Comment by xanoni** [comment]
https://www.elliptic.co/resources/defi-risk-regulation-and-the-rise-of-decrime

This has some interesting (and quite depressing) perspectives on how the whole compliance space is going to evolve.

Can enter fake info to download.

**Comment by xanoni** [comment]
Here is another report that beaks down the recent FATF guidance:

https://www.elliptic.co/resources/fatf-virtual-asset-guidance-what-you-need-to-know (again, non-working fake email is fine)

There is more interesting stuff here: https://www.elliptic.co/resources

In general, I think it's worth subscribing to the email newsletter of the crypto analytics companies (Chainalysis, Elliptic, TRM, Crystal, ...):

1. https://blog.chainalysis.com/subscribe
2. https://info.elliptic.co/reg-affairs-subscribe-elliptic
3. https://www.trmlabs.com/trm-insights (form at bottom of site)
4. https://crystalblockchain.com/news-and-resources/

Some of the also have repos on GitHub with interesting things in it ;-) ... e.g., https://github.com/trisacrypto/

**Comment by erciccione** [comment]
People seem to have understood that our interest in investigating the legal status of Haveno comes from the desire of becoming regulation compliant. Our intent is to make sure there is nothing in the trade protocol which could make us subject to regulations. Would be irresponsible and dangerous for both users and operators to launch something like Haveno without making this investigation first.

Our mistake was to give for assumed people would understand we have no interest in Haveno being regulation compliant, but also no interest in going to prison because something we oversaw in the protocol makes us subject of regulations. Since this is being misunderstood for us wanting to comply with regulation (something that would defeat the entire point of Haveno), we are closing this issue. This analysis will be made privately if needed, so that people don't get triggered for no reason.
