### ISSUE TITLE
Organize complete backup of the repositories

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#2]
Having our infrastructure on GitHub is a risk, we should organize backups to make sure code, issues, PRs, etc would be stored somewhere safe in case of a takedown. Something similar to what Monero does would be good.

**Comment by cirocosta** [comment]
> Something similar to what Monero does would be good.

what's done there? at first I thought https://repo.getmonero.org/users/monero-project/projects would have a mirror but I was actually wrong

**Comment by erciccione** [comment]
> what's done there? at first I thought https://repo.getmonero.org/users/monero-project/projects would have a mirror but I'm actually wrong
That's the mirror of github.com/monero-project/monero-site. Everything else is archived with https://backhub.co.
