### ISSUE TITLE
First public Haveno meeting Wednesday 14th at 17.00 UTC

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#3]
We will have the first Haveno meeting in #haveno-dev (matrix and Freenode) Wednesday 10th April at 17.00 UTC

Points in discussion (they could change):

1. Updates about current status of the project
2. Next steps 
2. Expansion of the community on social medias
3. Discuss logos and decide which one is best (#1)
4. Questions from the community
5. Suggestions from the community

The log will be added to this repository.

**Comment by erciccione** [comment]
Pinging @haveno-dex/design @haveno-dex/developers FYI.

**Comment by niyid** [comment]
Hello @erciccione @wooser

Is the chat group on Keybase still active? I need help with access to chat
with you and the group.

**Comment by SamsungGalaxyPlayer** [comment]
@niyid please make a Matrix account and join the #haveno-dev room.

Account creation steps: https://forum.monero.space/d/83-join-the-monero-core-team-matrix-server

**Comment by erciccione** [comment]
> Is the chat group on Keybase still active?

it is not. We are on matrix only now. You can register an account as @SamsungGalaxyPlayer suggested and then join #haveno and #haveno-dev

**Comment by niyid** [comment]
Ah. Great. Thanks a lot.

**Comment by erciccione** [comment]
Logs: https://github.com/haveno-dex/haveno-meta/blob/master/meeting-logs/first-meeting-15-04-2021.txt
