### ISSUE TITLE
Document bounty process

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#5]

**Comment by amzinglyrwarded** [comment]
I have some experience programming in Java and I am a huge advocate and supporter of XMR. 

How can I join the development team or become a tester? (When I say Java, mostly android experience. I have an app and researching how to implement firebase into my app)

**Comment by erciccione** [comment]
hi @amzinglyrwarded, good to hear! The best place to start is by joining the dev room on matrix and freenode `#haveno-dev`. If you wish to be immediately active and be pinged when there are dev-related discussions, we could add you to the "developers" team here on Github.
