### ISSUE TITLE
Haveno meeting Sunday 16th 16:00 UTC

### ISSUE THREAD

**Issue by erciccione** [haveno-dex/haveno-meta#7]
Meeting in `#haveno` (last time was at `#haveno-dev`).

Agenda:

- Updates to the community
  - Progresses and priorities
  - Bounty program
- Questions from the community

The log will be added to this repository.

**Comment by erciccione** [comment]
ping @haveno-dex/design @haveno-dex/developers

**Comment by Fierfek-TrCo** [comment]
Hello.

**Comment by erciccione** [comment]
Added logs with #9. Closing.
